### ISSUE TITLE
Empty reply from server when running curl

### ISSUE THREAD

**Issue by aymanapatel** [nicholasjackson/envoy-experiments#3]
I have clone the repo and tried to run tcp-loadbalancing

```
shipyard run ./tcp-loadbalancing
```

The CLI runs properly, creating 4 containers

```
docker ps
CONTAINER ID        IMAGE                                 COMMAND                  CREATED             STATUS              PORTS                NAMES
22255205b9a0        shipyardrun/ingress:latest            "ingress --service-n…"   7 seconds ago       Up 5 seconds        0.0.0.0:80->80/tcp   frontend.ingress.shipyard.run
5c7388ad994f        envoyproxy/envoy-alpine:v1.13.1       "/docker-entrypoint.…"   9 seconds ago       Up 7 seconds        10000/tcp            envoy.container.shipyard.run
2644ed8272d8        nicholasjackson/fake-service:v0.8.0   "/app/fake-service"      9 seconds ago       Up 7 seconds                             api1.container.shipyard.run
aa365ad6c278        nicholasjackson/fake-service:v0.8.0   "/app/fake-service"      9 seconds ago       Up 7 seconds                             api2.container.shipyard.run
```

But curl localhost gives empty server response.

```
curl localhost
curl: (52) Empty reply from server
```

**Comment by nicholasjackson** [comment]
I am terrifically sorry @AymanArif the examples in the repo did not work with the latest version of Shipyard. Shipyard changed it's internal naming convention for containers from `name.container.shipyard` to `name.contianer.shipyard.run` a few months ago. I am actually working on a Shipyard issue right now to make sure problems like this never happen again.

I have updated the example now for TCP and Routing and given both a quick test. They should be working now.

Thank you so much for raising this.

**Comment by aymanapatel** [comment]
Thanks @nicholasjackson for the swift reply. I have updated and it works now!
Cheers! :smile:
